"""empty message

Revision ID: 2c30407aab9a
Revises: fc34a3567b33
Create Date: 2022-06-14 14:27:28.537866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c30407aab9a'
down_revision = 'fc34a3567b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stripeCustomerId', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stripeSubscriptionId', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='stripe_customer_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stripe_customer_pkey')
    )
    # ### end Alembic commands ###
