"""empty message

Revision ID: 33f11bfc8394
Revises: 2c30407aab9a
Create Date: 2022-06-14 14:55:48.292955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33f11bfc8394'
down_revision = '2c30407aab9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stripeCustomerId', sa.String(length=255), nullable=False),
    sa.Column('stripeSubscriptionId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_customer')
    # ### end Alembic commands ###
