"""empty message

Revision ID: fc34a3567b33
Revises: 77357a5f8d4d
Create Date: 2022-06-14 14:08:15.286831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc34a3567b33'
down_revision = '77357a5f8d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stripeCustomerId', sa.String(length=255), nullable=False),
    sa.Column('stripeSubscriptionId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stripe_customer')
    # ### end Alembic commands ###
